version: 1.2
workflows:
  - name: DummyVariantCallingWorkflow
    subclass: WDL
    primaryDescriptorPath: /DummyVariantCalling.wdl
    testParameterFiles:
    - /DummyVariantCalling.inputs.json
  - name: GetCRAMsFromBroadTerraWorkflow
    subclass: WDL
    primaryDescriptorPath: /GetCRAMsFromBroadTerra.wdl
    testParameterFiles:
    - /GetCRAMsFromBroadTerra.inputs.json
  - name: DepthOfCoverageWorkflow
    subclass: WDL
    primaryDescriptorPath: /DepthOfCoverage.wdl
    testParameterFiles:
    - /DummyVariantCalling.inputs.json
  - name: RuntimeOptionsTestWorkflow
    subclass: WDL
    primaryDescriptorPath: /RuntimeOptionsTest.wdl
    testParameterFiles:
    - /RuntimeOptionsTest.inputs.json
  - name: DockstoreVersionTesting
    subclass: WDL
    primaryDescriptorPath: /DockstoreVersionTesting.wdl
    filters:
      branches:
        - main
      tags:
        - VERTEST_*
